// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iecudbrhqkmzdjfnephs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImllY3VkYnJocWttemRqZm5lcGhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1NzMwODIsImV4cCI6MjA3NTE0OTA4Mn0.6pMvOcyugiNEOamlQbhwo5XomSTCsPzuSm2ho0JCdMM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});